// coverage:ignore file reason=generated
// Code generated by mockery v2. DO NOT EDIT.

package example

// MockStore is a generated mock of Store for use in tests.
type MockStore struct {
	data map[string]*Order
}

func (m *MockStore) Add(o *Order) {
	if m.data == nil {
		m.data = make(map[string]*Order)
	}
	m.data[o.ID] = o
}

func (m *MockStore) Get(id string) (*Order, bool) {
	o, ok := m.data[id]
	return o, ok
}
